on:
  push:
    branches:
      - dev
    # paths:
    #   - 'packages/ui/**'

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: ls
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # No other arguments should be used: https://github.com/google-github-actions/release-please-action/issues/941
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          release-type: node
      - name: Close, reopen and auto-merge PR, to trigger all necessary checks (https://github.com/googleapis/release-please/issues/922)
        if: steps.release.outputs.prs_created == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
          pr_number: "${{ steps.release.outputs.pr && toJSON(fromJSON(steps.release.outputs.pr).number) }}"
          pr_title: '[UI] Automatic Release'
        shell: bash
        run: |
          gh pr close ${{ env.pr_number }} -R ${{ github.repository }} || true
          gh pr reopen ${{ env.pr_number }} -R ${{ github.repository }} || true
          gh pr merge -R ${{ github.repository }} --merge --auto ${{ env.pr_number }} -b "" -t '⇄ PR-#${{ env.pr_number  }} | ${{ env.pr_title }}'