on:
  push:
    branches:
      - dev
    # paths:
    #   - 'packages/ui/**'

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      enable-pull-request-automerge
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # No other arguments should be used: https://github.com/google-github-actions/release-please-action/issues/941
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          command: manifest
          release-type: node
      # - name: Close, reopen and auto-merge PR, to trigger all necessary checks (https://github.com/googleapis/release-please/issues/922)
      #   if: steps.release.outputs.pr
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     pr_number: "${{ steps.release.outputs.pr && toJSON(fromJSON(steps.release.outputs.pr).number) }}"
      #     pr_title: '[UI] Automatic Release'
      #   shell: bash
      #   run: |
      #     gh pr merge -R ${{ github.repository }} --merge --auto ${{ env.pr_number }} -b "" -t '⇄ PR-#${{ env.pr_number  }} | ${{ env.pr_title }}'
      - name: Auto-merge pull request
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
          # to trigger other workflows, pass PAT token instead of GITHUB_TOKEN
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
